# secrets.toml

[general]
# General application secrets
app_key = "your_app_key_here"

[database]
# Database credentials
username = "your_db_username"
password = "your_db_password"
host = "your_db_host"
port = 5432
database = "your_db_name"

[api]
# API credentials
google_api_key = "your_google_api_key"
